### ISSUE TITLE
MRU_Exclude_Files by filetype on Windows machine?

### ISSUE THREAD

**Issue by llinfeng** [yegappan/mru#10]
What is the syntax to ignore those files ending with .tmp or .log, through MRU_Exclude_Files?

I am running Windows 8.1

All the best, 
- Linfeng

**Comment by yegappan** [comment]
To exclude the files with the .tmp and .log extension, you can set the MRU_Exclude_Files variable
like shown below in your .vimrc file:

   let MRU_Exclude_Files='\.log$\|\.tmp$'
