### ISSUE TITLE
Enhancement: if hidden is set always open in current window

### ISSUE THREAD

**Issue by mlippert** [yegappan/mru#13]
Right now, if you use enter to open a file which is not currently open, and the buffer in the current window is modified, the new file will always be opened in a new window.

I'd like to propose that behavior is only true when `hidden` is not set. If `hidden` is set, then the buffer in the current window is replaced w/ the file being opened even if it is modified.

If `hidden` is set and multiple files are being opened, the last one should replace the file in the current window and the others should be opened hidden.

This would mesh well w/ those of us using a buffer manager (such as [buffet](https://github.com/sandeepcr529/Buffet.vim)).

**Comment by yegappan** [comment]
Modified the plugin to take into account the 'hidden' option when opening files from the MRU list.

**Comment by mlippert** [comment]
tested new version, works great, thanks.
