### ISSUE TITLE
MRU causes the Chinese can not normally show

### ISSUE THREAD

**Issue by zyqhi** [yegappan/mru#17]
After installed mru through vuddle，Chinese in macvim(7.4) can not normally show, but it is normal in terminal.

![screen shot 2015-05-24 at 1 28 48 pm](https://cloud.githubusercontent.com/assets/1908908/7786839/021d0d68-0219-11e5-9097-26be15ab63ea.png)

**Comment by yegappan** [comment]
Can you check the value of the 'encoding' setting? Is it properly set to display the Unicode characters? Are you able to reproduce this problem with the latest version of Vim and the MRU plugin?
