### ISSUE TITLE
FZF support

### ISSUE THREAD

**Issue by jeanCarloMachado** [yegappan/mru#23]
Would be great to use fzf on the MRU list. If you like the idea I can send a PR.

**Comment by yegappan** [comment]
Hi,
Yes. Please do send the patch.
Regards,Yegappan
    On Friday, September 14, 2018, 10:25:39 PM PDT, Jean Carlo Machado <notifications@github.com> wrote:  
 
 
Would be great to use fzf on the MRU list. If you like the idea I can send a PR.

**Comment by 29ayush** [comment]
@jeanCarloMachado Did you by any chance worked on this. I really want a mru with fzf, the other plugins available are not as good as this.

**Comment by yegappan** [comment]
I have added a FZFMru command to integrate MRU with the FZF plugin (e318b2e).
