### ISSUE TITLE
Addition of strcharpart changes Vim version requirements

### ISSUE THREAD

**Issue by alex-tsaptsinos** [yegappan/mru#24]
Just updated today and noticed that in commit 7ef8683b9809458c1ed230d7fde7f851dcac9f2b the function `strcharpart` was added to replace `strpart`.

This function was added to vim in commit vim/vim@58de0e2 on April 14 2016 which is equivalent to the patch level 7.4.1730.

Therefore I believe you either need to update the requirements in the README to this version of Vim, or revert to using `strpart` again.

Hope this helps!

**Comment by rifuso** [comment]
I just ran into this problem with VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 30 2018 19:56:57)

Error detected while processing function <SNR>17_MRU_LoadList..<SNR>17_MRU_Refresh_Menu..<SNR>17_MRU_add_files_to_menu:
line   13:
E117: Unknown function: strcharpart
E15: Invalid expression: strcharpart(dir_name, 0, 10) . '...' . strcharpart(dir_name, len - 20)
E117: Unknown function: strcharpart
E15: Invalid expression: strcharpart(dir_name, 0, 10) . '...' . strcharpart(dir_name, len - 20)
E117: Unknown function: strcharpart
E15: Invalid expression: strcharpart(dir_name, 0, 10) . '...' . strcharpart(dir_name, len - 20)
Press ENTER or type command to continue

**Comment by yegappan** [comment]
Fixed by  commit (d69f941)
