### ISSUE TITLE
buffer write on :MRU

### ISSUE THREAD

**Issue by cruisercoder** [yegappan/mru#27]
What's the recommend way to handle writing the buffer when invoking MRU to avoid opening a new window when there are changes in the current buffer?  autowrite / autowriteall does not seem to apply and it would make using and explaining MRU to new users.

**Comment by cruisercoder** [comment]
My current solution below (mapped to space), which saves the any buffer changes before calling MRU.

nnoremap <Space> :update<bar>:MRU<cr>

**Comment by byron-hawkins** [comment]
This doesn't work for me, so it must depend on some part of your `.vimrc` that is not shown here. I use this instead (to open MRU using ctrl+w):

    noremap <C-w> :up!<CR>:MRU<CR>
