### ISSUE TITLE
Ability to delete files from MRU list by pressing d key

### ISSUE THREAD

**Issue by jm3** [yegappan/mru#3]
Please? :)

**Comment by ozra** [comment]
I plugged in MRU just five minutes ago (why on earth not 20 years ago!).
First thought: _"Awesome!"_.
Second thought: "Why doesn't 'd' delete an entry?".

Just saying :+1:.

**Comment by yegappan** [comment]
Committed 805bde4775601ebb297bdd0814867de3caa0a8c3 to add support for deleting an entry.
