### ISSUE TITLE
how to close mru window?

### ISSUE THREAD

**Issue by joe23rep** [yegappan/mru#32]
is there a way to close the mru window? i open it via shortcut but to close it ive to either select a new file from its list or click to open the file im currently working on. 

is there a way to toggle mru? neither esc nore q or again :MRU do anything

**Comment by Arnie97** [comment]
`:q`, `ZQ`, or anything that closes a buffer should just work...

**Comment by yegappan** [comment]
The 'q' key is mapped to close the window in the MRU window. So you can press q to close the MRU window. You can also use any of the Vim commands that close a window.
