### ISSUE TITLE
dd: delete files from MRU list

### ISSUE THREAD

**Issue by mralusw** [yegappan/mru#35]
Would be nice to have a way to remove entries from MRU list (without resorting to external editor) -- e.g. when files are moved, deleted, or are symlink aliases of other MRU entries

**Comment by yegappan** [comment]
Committed a0a8c3 to add support for removing entries from the MRU list.

**Comment by mralusw** [comment]
The problem with using 'd' instead of the standard vim 'dd' is that my Vim hangs until I press another key after 'd' (such as right arrow). I have `set notimeout ttimeout` in my vimrc as I don't want key code sequences to time out.

**Comment by yegappan** [comment]
The mappings created by the MRU plugin are all buffer-local mappings and apply only to the MRU window. So the 'd' key mapping to delete an entry works only in the MRU window. In other windows, the 'd' key is not mapped by MRU and you should not see any delay in using the 'd' key in other window. Are you seeing a delay in using the 'd' key in the MRU window?
