### ISSUE TITLE
Error writing MRU list file when re-sourcing init.vim

### ISSUE THREAD

**Issue by mroavi** [yegappan/mru#38]
Initially, I had the following line in my `init.vim` to remember where the MRU list file is stored:
```vim
let MRU_File = '$HOME/.vim_mru_files'
```
I noticed that if I re-source my `init.vim` then I get the following error whenever the MRU plugin tries to save the MRU list file:
```vim
Error detected while processing function <SNR>43_MRU_AddFile[59]..<SNR>43_MRU_SaveList:
line    4:
E482: Can't open file $HOME/.vim_mru_files for writing: no such file or directory
[which-key] <space> e is undefined
```
Since the custom path I'm setting is the same as the default one, I disabled it and the problem went away. However, other people that might actually want to store their MRU list file in another place, might run into this problem. Just wanted to point this out.

Here is a minimal `init.vim`:
```vim
call plug#begin(stdpath('data') . '/plugged')
Plug 'yegappan/mru'
call plug#end()

let MRU_File = '$HOME/.vim_mru_files'
```

**Comment by yegappan** [comment]
The environment variables (like $HOME) in the MRU_File variable are expanded
only when loading the plugin. If the variable is changed after that, then the environment
variables are not expanded, which results in this error. I have modified the plugin to
use a script local variable for MRU_File after loading the plugin. It should fix this error.
Can you try out the latest version of the plugin?

**Comment by mroavi** [comment]
Problem solved. Thanks for the accompanying explanation by the way.
