### ISSUE TITLE
Increase FZFMru Window Height

### ISSUE THREAD

**Issue by ranelpadon** [yegappan/mru#41]
If I set this:
```
let MRU_Window_Height = 40
```

the `:MRU` command window will increase:
<img width="778" alt="Screen Shot 2021-05-14 at 2 38 07 PM" src="https://user-images.githubusercontent.com/4292088/118231723-10983e00-b4c2-11eb-9e2d-a8628b13dd10.png">

but it has no effect in the `:FZFMru` command:
<img width="671" alt="Screen Shot 2021-05-14 at 2 35 47 PM" src="https://user-images.githubusercontent.com/4292088/118231833-3b829200-b4c2-11eb-8d63-a7e8915fae57.png">

I think they should follow similar height setting/value? Is there a workaround for increasing the `:FZFMru` command?

By the way, thanks for this really useful plugin. :)

**Comment by yegappan** [comment]
I have pushed the 3e106d commit to use the MRU window height for the FZF window.

**Comment by ranelpadon** [comment]
Confirmed working. Thanks a lot! :)
