### ISSUE TITLE
Why not just use `:browse oldfiles` and `v:oldfiles`?

### ISSUE THREAD

**Issue by subnut** [yegappan/mru#42]
If vim is compiled using `+viminfo` feature (which it usually is), or if using neovim,  
then there is an in-built feature which you can use!
```
:browse oldfiles
```
Which shall show a list of the most recently-opened files!

<br>

Also, the variable `s:MRU_files` is serving the same purpose as the variable `v:oldfiles`! Why not just use `v:oldfiles` ?  
See -
```
:help v:oldfiles
```

**Comment by yegappan** [comment]
When you run multiple instances of Vim simultaneously (which is common in a developer
workflow), then the v:oldfiles value will not be merged across the sessions. The MRU plugin
will write the MRU file and read back the updated values. This is in addition to the various
other features supported by the MRU plugin (including fuzzy searching filenames,
showing the names in a usable window, etc.). Also note that the MRU plugin was
originally developed back in 2003 (way before the v:oldfiles variable was added to Vim).

**Comment by subnut** [comment]
Thanks for the clarification!
