### ISSUE TITLE
Feature request: unique file name in MRU list

### ISSUE THREAD

**Issue by mroavi** [yegappan/mru#43]
It is quite common to have different files with the same name but in different dirs (e.g. `Makefile`)
With Neovim, this is also quite common:

![image](https://user-images.githubusercontent.com/19517248/127784947-91d6bcf4-c065-4383-a9a0-1bf0448795ac.png)

I find it a little bit annoying having to look at the path (right-hand side in the image) to identify which is the file you want to open.

Would it be possible to include  "directory name + file name" for repeated file names in the MRU list?

E.g. the example above would change to:

**nvim/init.lua** (/home/mroavi/dotfiles/nvim/.config/nvim/init.lua)
**mrv/init.lua** (/home/mroavi/dotfiles/nvim/.config/nvim/lua/mrv/init.lua)
**plugins/init.lua** (/home/mroavi/dotfiles/nvim/.config/nvim/lua/mrv/plugins/init.lua)
**tender/init.lua** (/home/mroavi/repos/tender.nvim/lua/tender/init.lua)
**custom.vim** (/home/mroavi/dotfiles/nvim/.config/nvim/lua/mrv/custom.vim)

(I know that plugins that display buffer names in the tabline have this functionality, e.g. [vim-buftabline](https://github.com/ap/vim-buftabline))

**Comment by yegappan** [comment]
The format of the file names displayed in the MRU window is controlled by the
MRU_Filename_Format variable. You can set this variable as shown below to get
the format you are describing:

let MRU_Filename_Format = {
                \ 'formatter': "fnamemodify(v:val, ':p:h:t') .. '/' .. fnamemodify(v:val, ':p:t') .. ' (' .. v:val .. ')'",
                \ 'parser':'(\zs.*\ze)',
                \ 'syntax': '^.\{-}\ze('}

**Comment by mroavi** [comment]
Thanks a lot! This works well. The only problem is that the blue highlight color does not appear now. Any idea how I could re-enable it?

**Comment by yegappan** [comment]
In the MRU_Filename_Format variable, did you set the 'syntax' value
properly? With the above setting in my setup, the filename is properly
highlighted in the MRU window.

**Comment by mroavi** [comment]
Hmm, that's strange. In my case, the highlight disappears. I have a vim function that lets me know the highlight under the cursor. Without setting `MRU_Filename_Format`, the function outputs `MRUFileName`, but after setting this option (as suggested above) no highlight is outputted.

![Peek 2021-08-03 17-22_mru_highlight_issue](https://user-images.githubusercontent.com/19517248/128041889-8c3059ef-af2a-4ee8-b419-f2f10131d40e.gif)

**Comment by yegappan** [comment]
What is the output of the ":syntax" command in the MRU window in both cases?

**Comment by mroavi** [comment]
Case 1:
```vim
:syntax
--- Syntax items ---
MRUFileName    xxx match /^.\{-}\ze(/
                   links to Identifier
Press ENTER or type command to continue
```
Case 2:
```vim
:syntax
--- Syntax items ---
MRUFileName    xxx match /^.{-}\ze(/
                   links to Identifier
Press ENTER or type command to continue
```

**Comment by yegappan** [comment]
What is the output of the ":highlight Identifier" command in the MRU window?
Do you use any other plugin?

**Comment by mroavi** [comment]
With `let MRU_Filename_Format` defined as you suggest:

```vim
:highlight Identifier
Identifier     xxx cterm=bold ctermfg=14 guifg=#73cef4
Press ENTER or type command to continue
```

Yes, I use many other plugins. I will disable them all except MRU to see if it's conflicting with another plugin.

**Comment by mroavi** [comment]
I disabled all plugins except MRU. The behavior is the same as described above.

**Comment by mroavi** [comment]
Here is a minimalistic init.vim to reproduce the problem:

```vim
" run with: nvim -u test.vim

set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'yegappan/mru'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close

let MRU_Filename_Format = {
\ 'formatter': "fnamemodify(v:val, ':p:h:t') .. '/' .. fnamemodify(v:val, ':p:t') .. ' (' .. v:val .. ')'",
\ 'parser':'(\zs.*\ze)',
\ 'syntax': '^.{-}\ze('}
```

**Comment by yegappan** [comment]
When I suggested the setting for MRU_Filename_Format, I somehow
missed out the backslash before the "{" in the 'syntax' value.
Can you try using the value '^.\{-}\ze(' for the 'syntax' key?

**Comment by mroavi** [comment]
Fixed! These regular expressions look like hieroglyphs to me. Thanks a lot!
