### ISSUE TITLE
Question: how can I filter the current buffer from the MRU list?

### ISSUE THREAD

**Issue by mroavi** [yegappan/mru#44]
Since jumping to the current (active) buffer doesn't make sense, is there a way to filter it from the displayed list. Or equivalently, is there a way to filter the first entry from the displayed list?

**Comment by mroavi** [comment]
I found a hack:

```vim
" In mru/plugin/mru.vim
...
    " No search pattern specified. Display the complete list
    let m = copy(s:MRU_files)[1:]
...
```

However, I'm still interested in knowing how to do this without having to modify the source code (if possible of course)

**Comment by yegappan** [comment]
The MRU window display the entire MRU list (by default). Displaying the current buffer
is useful, if you want to open the current file in a different window using the o, O, v,
t or p commands.

**Comment by mroavi** [comment]
That makes sense. I haven't thought about it. I arrived at a different solution that doesn't involve changing the source code. I added a `j` to the end of the mapping so that the cursor moves immediately to the second entry each time the MRU list is displayed. I think I'm happy with this for now. Thanks!
