### ISSUE TITLE
Fetaure request: Add option to set vim's alternate file to the first entry in the MRU list at startup

### ISSUE THREAD

**Issue by mroavi** [yegappan/mru#49]
My feature request is to add an option that enables setting vim's alternate file to the first entry in the MRU list at startup.
I don't understand why vim doesn't provide an option to remember the alternate file. Not even using Sessions.
Let me know what you think.

**Comment by mroavi** [comment]
Here is an initial idea. This is still missing checking whether the option is set:

```vim

...

" Load the MRU list on plugin startup
call s:MRU_LoadList()

" Set fist entry in MRU list as alternate file 
let s:bufnr = bufadd(s:MRU_files[0])
let @#=s:MRU_files[0]

...
```

**Comment by yegappan** [comment]
This is a good idea. I will make this a configurable option (default is disabled). I will push a change for this.

**Comment by yegappan** [comment]
This is addressed by f30ba874a996fdcb5e4ec6060d7cefe6ff247055.

**Comment by mroavi** [comment]
I noticed that the new patch does not work on nvim because of this check:

```vim
&& (v:version >= 802 || has('patch-8.1.1610'))
```

Could you add support for nvim as well?

**Comment by yegappan** [comment]
I have pushed a commit to check for nvim also? Can you try that out?

**Comment by mroavi** [comment]
Works great now. Thanks.
