### ISSUE TITLE
:FZFMru shows changes only on the second call

### ISSUE THREAD

**Issue by OlegPQ** [yegappan/mru#54]
I ran into the following behavior. `:FZFMru` shows changes only on the second call, namely:
Open your _MRU_File_, add or change existing lines in it. call `:FZFMru`, the changes are not reflected. call `:FZFMru` again, the changes are displayed.
When I call `:MRU`, the changes are immediately visible, i.e. on the first call.

Is this some kind of feature? Why might this be happening?

File: mru.vim
Version: 3.10.2

**Comment by yegappan** [comment]
Are you manually adding and removing file names from the MRU file (MRU_File) outside of the plugin?

**Comment by OlegPQ** [comment]
Yes.

:MRU - shows the changes on the first call.
:FZFMru - shows changes only on the second call.

**Comment by yegappan** [comment]
This is a bug. The call to read the MRU file again before invoking FZF is missing. I will add this in the next commit.

**Comment by yegappan** [comment]
I have committed 148f71bd47bdb2af8c639694863910b6e551aaa4 to address this issue.
