### ISSUE TITLE
Error detected while processing mru.vim [1040]..function <SNR>50_MRU_LoadList[24]

### ISSUE THREAD

**Issue by Griiid** [yegappan/mru#60]
Hi, I'm using mru in bash in macOS, this is not the first time I install it, I reinstall my MacBook and I don't know how this error happens.

Here's the related neovim log:

```
sourcing "/Users/eddiehsu/.vim/plugged/mru/plugin/mru.vim"
Error detected while processing /Users/eddiehsu/.vim/plugged/mru/plugin/mru.vim[1040]..function <SNR>50_MRU_LoadList[24]..<SNR>50_MRU_Refresh_Menu:
line   12:
E329: No menu "&File"
Error detected while processing /Users/eddiehsu/.vim/plugged/mru/plugin/mru.vim[1040]..function <SNR>50_MRU_LoadList[24]..<SNR>50_MRU_Refresh_Menu:
line   17:
E328: Menu only exists in another mode
finished sourcing /Users/eddiehsu/.vim/plugged/mru/plugin/mru.vim
```

- macOS version: 12.5.1
- bash version: 5.2.0(1)-release
- Neovim version: 0.8.0

**Comment by yegappan** [comment]
Line 12 in the MRU_Refresh_Menu() function in mru.vim is:
```
silent! unmenu &File.&Recent\ Files
```

This should ignore any generated error messages.  So I am not sure why Neovim is not ignoring the errors.  I tried Neovim 0.8.0 (Qt) on a MS-Windows system and couldn't reproduce this issue.  How do you invoking the GUI version of NeoVim? What Neovim options do you enable?

**Comment by oakmegaeddie** [comment]
hmm... that's strange, thank u telling me that it is `silent`, it may be a key point for me.

There's a lot of other erros, not only about MRU, so maybe it's not the issue of MRU.
I've added a lot of settings in `.vimrc` and related files, so I can't put my configs here.
I'm using terminal version, not GUI version NeoVim.
I'll try to remove all settings & plugins, and then only install MRU, I will update the result.

**Comment by Griiid** [comment]
Okay, it's not the issue of MRU, since it works okay when I only put follow in `.vimrc`:

```vimrc
call plug#begin('~/.vim/plugged')
Plug 'yegappan/mru'
call plug#end()
```

I'll try to find out the real problem, thank you every much!

**Comment by Griiid** [comment]
Sorry, I found there's still the same error log, I didn't find it because I didn't search with case-sensitive `Error`

**Comment by Griiid** [comment]
I realize that it will always a error log there, and with `silent!` it will not prompt message in neovim.
I saw it through command `nvim xxx -V9nvim.log`, the error message will output in `nvim.log` only.
Thank you!
