### ISSUE TITLE
option to change $HOME/.vim_mru_files path

### ISSUE THREAD

**Issue by BeyondMagic** [yegappan/mru#62]
We should be able to set where its file should be, with its default being `$HOME/.vim_mru_files` on Unix-systems.

It feels cluttered to have a home with too many files from a specific plugin from a specific program.

**Comment by yegappan** [comment]
You can already set the name and location of the file containing the list of MRU file names.  This is controlled by setting the MRU_File variable.  You can set this in your .vimrc file:

   let MRU_File = '/path/to/my_mru_file'

**Comment by BeyondMagic** [comment]
I am dumb, thank you.
